name: .NET Desktop

on:
  push:
    branches: none    # [ "main" ]
  pull_request:
    branches: none    # [ "main" ]

  # 액션탭으로 부터 이 워크플로우 수정 실행을 허용가능
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 

    env:
      Solution_Name: TestConsoleApp.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      working-directory: TestConsoleApp

    steps:
    - name: 닷넷 체크아웃
      uses: actions/checkout@v4

    # .NET 인스톨?
    - name: 닷넷 셋업
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 의존성 복구
    - name: 애플리이션 복구
      run: dotnet restore

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: MSBuild
      run: dotnet build --no-restore
      
    # 유닛테스트는 없음
    - name: 유닛테스트 실행
      run: dotnet test --no-build --verbosity normal
